apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bff-store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/viniciusfca/kind-kong.git
    targetRevision: HEAD
    path: apps/bff-store
  destination:
    server: https://kubernetes.default.svc
    namespace: bff-store
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true