apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.konghq.com
    targetRevision: "2.20.0"
    chart: kong
    helm:
      parameters:
      - name: "ingressController.installCRDs"
        value: "false"
        forceString: true # ensures that value is treated as a string
      values: |
        podAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8100"
        plugins:
          configMaps:
            - name: kong-plugin-keycloak-plugin
              pluginName: keycloak-plugin
        extraVolumes:
          - name: kong-plugins
            configMap:
              name: kong-plugin-keycloak-plugin
        extraVolumeMounts:
          - name: kong-plugins
            mountPath: /usr/local/share/lua/5.1/kong/plugins/keycloak-plugin
        env:
          KONG_LUA_PACKAGE_PATH: "/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/share/lua/5.1/kong/plugins/keycloak-plugin/?.lua;;"
        extraInitContainers:
          - name: install-plugins
            image: kong:2.8.0-alpine
            command: ["/bin/sh", "-c"]
            args:
              - |
                luarocks install lua-cjson
                luarocks install lua-resty-http
                luarocks install lua-resty-jwt
                luarocks install luasocket
            volumeMounts:
              - name: kong-plugins
                mountPath: /usr/local/share/lua/5.1/kong/plugins/keycloak-plugin
        
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true