---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cepapi-ingress
  labels:
    app: cepapi-ingress
spec:
  selector:
    matchLabels:
      app: cepapi-ingress
  replicas: 1
  template:
    metadata:
      labels:
        app: cepapi-ingress
    spec:
      containers:
      - name: echo
        image: viniciusfca/cepapi:latest
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
            cpu: 200m