---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bff-store
  labels:
    app: bff-store
spec:
  selector:
    matchLabels:
      app: bff-store
  replicas: 1
  template:
    metadata:
      labels:
        app: bff-store
    spec:
      containers:
      - name: echo
        image: viniciusfca/bff-store:latest
        ports:
        - containerPort: 4000
          protocol: TCP
        resources:
          requests:
            cpu: 200m