---
kind: Service
apiVersion: v1
metadata:
  name: bff-store-service
  labels:
    app: bff-store
spec:
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: bff-store