---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cepapi
  labels:
    app: cepapi
spec:
  selector:
    matchLabels:
      app: cepapi
  replicas: 1
  template:
    metadata:
      labels:
        app: cepapi
    spec:
      containers:
      - name: echo
        image: viniciusfca/cepapi:latest
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
            cpu: 200m


---
apiVersion: configuration.konghq.com/v1
kind: KongService
metadata:
  name: cepapi
spec:
  name: cepapi
  url: http://cepapi-service:5000
  route:
    methods:
    - GET
    - POST
    - PUT
    - DELETE
    paths:
    - /cep